### Listar categorias
GET http://localhost:5008/api/categoria/listar

### Cadastrar categoria
POST http://localhost:5008/api/categoria/cadastrar
Content-Type: application/json

{
    "nome" : "Alimentos"
}