### Requisição para a raiz da API
GET http://localhost:5195

###
GET http://localhost:5195/produto/listar

### Buscar Produto
GET http://localhost:5195/produto/buscar/Banana

### Cadastrar Produtos
POST http://localhost:5195/produto/cadastrar/
Content-Type: application/json

{
    "Id" : "4",
    "Nome" : "Banana",
    "Preco" : 10.00,
    "Quantidade" : 5 
}

### Alterar Produto
PUT http://localhost:5195/produto/alterar/1
Content-Type: application/json

{
    "Nome": "Produto A Modificado",
    "Preco": 24.99,
    "Quantidade": 15
}

### Deletar Produto
DELETE http://localhost:5195/produto/deletar/3

 
